import { useEffect, useState } from "react";
import type { BlockchainStatus, CommitteeResponse } from "../../../shared/api";
import type { Validator } from "../../../shared/types";
import { apiClient } from "../api/client";
import { Badge, Card, ErrorNotice, Loading, PageHead, short, Stat } from "../ui";

export function ValidatorStatusPage() {
  const [status, setStatus] = useState<BlockchainStatus | null>(null); const [validators, setValidators] = useState<Validator[]>([]); const [validatorsLoaded, setValidatorsLoaded] = useState(false); const [committee, setCommittee] = useState<CommitteeResponse | null>(null); const [statusError, setStatusError] = useState(""); const [validatorError, setValidatorError] = useState(""); const [committeeError, setCommitteeError] = useState("");
  useEffect(() => { apiClient.getBlockchainStatus().then(setStatus).catch((e) => setStatusError(e instanceof Error ? e.message : "Unable to load blockchain status.")); apiClient.getValidators().then((value) => { setValidators(value); setValidatorsLoaded(true); }).catch((e) => setValidatorError(e instanceof Error ? e.message : "Unable to load validators.")); }, []);
  useEffect(() => { if (!status) return; apiClient.getCommittee(status.lastFinalizedHeight).then(setCommittee).catch((e) => setCommitteeError(e instanceof Error ? e.message : "Unable to load committee.")); }, [status]);
  if (!status && !statusError) return <Loading />;
  const chainHealthy = Boolean(status?.healthy && !statusError);
  const finalityHealthy = Boolean(status && status.finalityLag === 0);
  const committeeAvailable = Boolean(committee && !committeeError);
  const validatorsAvailable = Boolean(!validatorError && validatorsLoaded);
  const overallHealthy = chainHealthy && finalityHealthy && committeeAvailable && validatorsAvailable;
  const state = (ok: boolean, unavailable = false) => <Badge tone={ok ? "active" : unavailable ? "pending" : "danger"}>{ok ? "HEALTHY" : unavailable ? "UNAVAILABLE" : "DEGRADED"}</Badge>;
  return <><PageHead eyebrow="Permissioned network" title="Network health" description="Validator, finality, and committee status for the BEL operational network." action={state(overallHealthy, !status && !statusError)} /><Card><h2>Network signals</h2><div className="kv"><div className="k">Network RPC</div><div className="v">{state(chainHealthy, !status && !statusError)}</div><div className="k">Block production</div><div className="v">{state(chainHealthy, !status && !statusError)}</div><div className="k">Finalization</div><div className="v">{state(finalityHealthy, !status && !statusError)}</div><div className="k">Committee data</div><div className="v">{state(committeeAvailable, !committee && !committeeError)}</div><div className="k">Validator data</div><div className="v">{state(validatorsAvailable, !validatorsLoaded && !validatorError)}</div></div></Card>{statusError ? <ErrorNotice message={statusError} /> : status && <div className="grid grid-3" style={{ marginBottom: 20 }}><Stat label="Block height" value={status.height} /><Stat label="Last finalized" value={status.lastFinalizedHeight} /><Stat label="Finality lag" value={`${status.finalityLag} blocks`} tone={status.finalityLag === 0 ? "success" : "warning"} /></div>}{status && <Card><h2>Finalized committee</h2>{committeeError ? <ErrorNotice message="Committee data is unavailable from the configured network RPC." /> : committee ? <div className="kv"><div className="k">Requested height</div><div className="v">{committee.height}</div><div className="k">Validator IDs</div><div className="v mono">{committee.validatorIds.join(", ") || "No validators returned"}</div></div> : <Loading />}</Card>}{validatorError ? <ErrorNotice message="Validator data is unavailable from the configured network RPC." /> : <Card><h2>Validator set</h2><div className="table-wrap"><table><thead><tr><th>Validator</th><th>Public key</th><th>Joined</th><th>Status</th></tr></thead><tbody>{validators.map((v) => <tr key={v.validatorId}><td className="mono">{v.validatorId}</td><td className="mono">{short(v.publicKey, 26)}</td><td>{new Date(v.joinedAt).toLocaleDateString("en-IN")}</td><td><Badge tone={v.status === "ACTIVE" ? "active" : "danger"}>{v.status}</Badge></td></tr>)}</tbody></table>{!validators.length && <div className="empty">No validator data returned.</div>}</div></Card>}</>;
}
