// Owner: Person 5. Network/deployment/ABI configuration for the EVM adapter.
//
// Addresses come from contracts/deployments/<network>.json (written by
// contracts/script/Deploy.s.sol) and ABIs from contracts/abis/ (committed,
// generated by scripts/generate-abis.sh), so redeploying never needs a code
// change. Nothing secret is read from files; dev signer keys may only come
// from the environment and are refused in production.

import { existsSync, readFileSync } from "node:fs";
import { dirname, isAbsolute, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { getAddress, isAddress, type InterfaceAbi } from "ethers";
import { BlockchainError } from "./errors";

export const CONTRACT_NAMES = ["IdentityRegistry", "RoleRegistry", "AssetRegistry", "JobManager", "AuditRegistry"] as const;
export type ContractName = (typeof CONTRACT_NAMES)[number];

export type DeploymentFile = {
  network: string;
  chainId: number;
  deployer?: string;
  bootstrapAdminWallet?: string;
  blockNumber?: number;
  contracts: Record<ContractName, string>;
};

export type EvmChainConfig = {
  rpcUrl: string;
  deployment: DeploymentFile;
  abis: Record<ContractName, InterfaceAbi>;
  /** Blocks to wait after inclusion before reporting success. */
  confirmations: number;
  /** Max time to wait for a receipt. */
  txTimeoutMs: number;
  /** How often to poll for receipts/blocks (ethers defaults to 4000ms). */
  pollingIntervalMs?: number;
  /** DEVELOPMENT ONLY. Private keys the backend may sign with (local anvil). */
  devSignerKeys: string[];
};

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");

function resolveRepoPath(p: string): string {
  return isAbsolute(p) ? p : resolve(REPO_ROOT, p);
}

function readJson(path: string, what: string): unknown {
  if (!existsSync(path)) throw new BlockchainError("CONFIG", `${what} not found at ${path}`);
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch (cause) {
    throw new BlockchainError("CONFIG", `${what} at ${path} is not valid JSON`, undefined, { cause });
  }
}

export function parseDeployment(raw: unknown, source = "deployment"): DeploymentFile {
  const d = raw as Partial<DeploymentFile> | null;
  if (!d || typeof d !== "object" || typeof d.contracts !== "object" || d.contracts === null) {
    throw new BlockchainError("CONFIG", `${source} has no "contracts" object`);
  }
  const chainId = Number(d.chainId);
  if (!Number.isInteger(chainId) || chainId <= 0) throw new BlockchainError("CONFIG", `${source} has an invalid chainId`);
  const contracts = {} as Record<ContractName, string>;
  for (const name of CONTRACT_NAMES) {
    const addr = (d.contracts as Record<string, unknown>)[name];
    if (typeof addr !== "string" || !isAddress(addr)) {
      throw new BlockchainError("CONFIG", `${source} is missing a valid address for ${name}`);
    }
    contracts[name] = getAddress(addr);
  }
  return { ...d, network: String(d.network ?? "unknown"), chainId, contracts } as DeploymentFile;
}

export function loadDeployment(networkOrPath: string): DeploymentFile {
  const path = networkOrPath.endsWith(".json")
    ? resolveRepoPath(networkOrPath)
    : resolve(REPO_ROOT, "contracts/deployments", `${networkOrPath}.json`);
  return parseDeployment(readJson(path, "Deployment file"), path);
}

export function loadAbis(abiDir = "contracts/abis"): Record<ContractName, InterfaceAbi> {
  const dir = resolveRepoPath(abiDir);
  const abis = {} as Record<ContractName, InterfaceAbi>;
  for (const name of CONTRACT_NAMES) {
    const abi = readJson(resolve(dir, `${name}.json`), `ABI for ${name}`);
    if (!Array.isArray(abi)) throw new BlockchainError("CONFIG", `ABI for ${name} is not an array`);
    abis[name] = abi as InterfaceAbi;
  }
  return abis;
}

function positiveInt(value: string | undefined, fallback: number, name: string, min = 0): number {
  if (value === undefined || value === "") return fallback;
  const n = Number(value);
  if (!Number.isInteger(n) || n < min) throw new BlockchainError("CONFIG", `${name} must be an integer >= ${min}`);
  return n;
}

/**
 * Reads EVM adapter configuration from the environment:
 *   BEL_CHAIN_RPC_URL           required, e.g. http://127.0.0.1:8545
 *   BEL_CHAIN_DEPLOYMENT        network name (contracts/deployments/<name>.json) or a .json path; default "local"
 *   BEL_CHAIN_ABI_DIR           default contracts/abis
 *   BEL_CHAIN_CONFIRMATIONS     default 1
 *   BEL_CHAIN_TX_TIMEOUT_MS     default 30000
 *   BEL_CHAIN_POLL_INTERVAL_MS  default 1000
 *   BEL_CHAIN_DEV_SIGNER_KEYS   comma-separated keys, development only
 */
export function loadChainConfigFromEnv(env: NodeJS.ProcessEnv = process.env): EvmChainConfig {
  const rpcUrl = env.BEL_CHAIN_RPC_URL?.trim();
  if (!rpcUrl) throw new BlockchainError("CONFIG", "BEL_CHAIN_RPC_URL is required when BEL_BLOCKCHAIN=evm");

  const devSignerKeys = (env.BEL_CHAIN_DEV_SIGNER_KEYS ?? "").split(",").map((k) => k.trim()).filter(Boolean);
  if (devSignerKeys.length > 0 && env.BEL_ENV === "production") {
    throw new BlockchainError(
      "CONFIG",
      "BEL_CHAIN_DEV_SIGNER_KEYS is forbidden in production: user transactions must be signed on the managed device (ADR-016)",
    );
  }

  return {
    rpcUrl,
    deployment: loadDeployment(env.BEL_CHAIN_DEPLOYMENT?.trim() || "local"),
    abis: loadAbis(env.BEL_CHAIN_ABI_DIR?.trim() || undefined),
    confirmations: positiveInt(env.BEL_CHAIN_CONFIRMATIONS, 1, "BEL_CHAIN_CONFIRMATIONS", 1),
    txTimeoutMs: positiveInt(env.BEL_CHAIN_TX_TIMEOUT_MS, 30_000, "BEL_CHAIN_TX_TIMEOUT_MS", 1),
    pollingIntervalMs: positiveInt(env.BEL_CHAIN_POLL_INTERVAL_MS, 1_000, "BEL_CHAIN_POLL_INTERVAL_MS", 10),
    devSignerKeys,
  };
}
