import { existsSync, readFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { createConnection } from "node:net";
import { URL } from "node:url";

const root = process.cwd();

function loadEnvFile(path) {
  if (!existsSync(path)) return {};
  const values = {};
  for (const line of readFileSync(path, "utf8").split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)=(.*)\s*$/);
    if (match) values[match[1]] = match[2].replace(/^['"]|['"]$/g, "");
  }
  return values;
}

const fileEnv = { ...loadEnvFile(`${root}/.env`), ...loadEnvFile(`${root}/backend/.env`) };
const env = {
  ...fileEnv,
  ...process.env,
  BEL_RUN_INTEGRATION: "true",
  BEL_EVM_RPC_URL: process.env.BEL_EVM_RPC_URL || process.env.BEL_CHAIN_RPC_URL || "http://127.0.0.1:8545",
};

function fail(message) {
  console.error(`VERIFY BLOCKED: ${message}`);
  process.exit(1);
}

async function checkPostgres() {
  if (!env.DATABASE_URL) fail("DATABASE_URL is not configured. Set it in .env or the environment.");
  const url = new URL(env.DATABASE_URL);
  await new Promise((resolve, reject) => {
    const socket = createConnection({ host: url.hostname, port: Number(url.port || 5432), timeout: 1500 });
    socket.once("connect", () => { socket.destroy(); resolve(); });
    socket.once("timeout", () => { socket.destroy(); reject(new Error("connection timed out")); });
    socket.once("error", reject);
  }).catch((error) => fail(`PostgreSQL is not reachable at ${url.hostname}:${url.port || 5432} (${error.message}). Start docker compose postgres first.`));
  console.log(`PostgreSQL reachable at ${url.hostname}:${url.port || 5432}`);
}

async function checkEvm() {
  const rpc = env.BEL_EVM_RPC_URL;
  try {
    const response = await fetch(rpc, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "eth_chainId", params: [] }) });
    const body = await response.json();
    if (body.error || body.result !== "0x7a69") throw new Error(body.error?.message || `expected chain id 31337, got ${body.result}`);
  } catch (error) {
    fail(`EVM RPC is not reachable or is not Anvil chain 31337 at ${rpc} (${error.message}). Start the Docker evm-node service first.`);
  }
  console.log(`EVM reachable at ${rpc} (chain id 31337)`);
}

function run(command, args, extraEnv = {}) {
  console.log(`> ${command} ${args.join(" ")}`);
  const result = spawnSync(command, args, { cwd: root, stdio: "inherit", env: { ...env, ...extraEnv } });
  if (result.error) fail(`${command} could not start: ${result.error.message}`);
  if (result.status !== 0) process.exit(result.status ?? 1);
}

const npm = process.platform === "win32" ? "npm.cmd" : "npm";

await checkPostgres();
await checkEvm();
run(npm, ["run", "prisma:generate"]);
run(npm, ["run", "db:migrate"]);
// Backend EVM tests consume contracts/out, which is generated by the real
// Foundry run and deliberately excluded from source control.
run(npm, ["run", "test:contracts"]);
run(npm, ["run", "typecheck"]);
run(npm, ["run", "test", "--workspace=bel-backend"]);
