import { useEffect, useState } from "react";
import { ROLES, type Role } from "../../../shared/enums";
import type { EmployeeDirectoryEntry, PendingRegistration } from "../../../shared/api";
import { apiClient } from "../api/client";
import { Badge, Button, Card, Empty, ErrorNotice, PageHead, formatDate, short } from "../ui";

export function EmployeesPage() {
  const [pending, setPending] = useState<PendingRegistration[]>([]); const [active, setActive] = useState<EmployeeDirectoryEntry[]>([]); const [selected, setSelected] = useState<PendingRegistration | null>(null); const [viewed, setViewed] = useState<EmployeeDirectoryEntry | null>(null); const [role, setRole] = useState<Role>("ENGINEER"); const [form, setForm] = useState({ employeeId: "", department: "" }); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  const load = () => Promise.all([apiClient.getPendingRegistrations(), apiClient.getActiveEmployees()]).then(([p, a]) => { setPending(p); setActive(a); }).catch((e) => setError(e instanceof Error ? e.message : "Unable to load employee records.")); useEffect(() => { void load(); }, []);
  async function verify() { if (!selected) return; setBusy("verify"); try { await apiClient.verifyRegistration(selected.identity.identityId, form); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Identity verification failed."); } finally { setBusy(""); } }
  async function assign() { if (!selected) return; setBusy("role"); try { await apiClient.assignRole(selected.identity.identityId, { role }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Role assignment failed."); } finally { setBusy(""); } }
  async function activate() { if (!selected) return; setBusy("activate"); try { await apiClient.activateRegistration(selected.identity.identityId); setSelected(null); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Registration activation failed."); } finally { setBusy(""); } }
  const identity = selected?.identity; const verified = Boolean(identity?.verifiedAt && identity.employeeId && identity.department); const roleAssigned = Boolean(identity?.role);
  return <><PageHead eyebrow="Identity administration" title="Employees" description="Review pending registrations and view all active BEL employees and administrators." />{error && <ErrorNotice message={error} />}<Card><div className="notice"><strong>Supported registration flow</strong><br />Employees initialize their account from the sign-in screen. Administrators verify, assign, and activate pending registrations here.</div></Card>
    <Card><h2>Pending registrations <Badge tone="pending">{pending.length} pending</Badge></h2><div className="table-wrap"><table><thead><tr><th>Employee</th><th>Department</th><th>Device</th><th>Wallet</th><th>Submitted</th><th /></tr></thead><tbody>{pending.map((item) => <tr key={item.identity.identityId}><td><strong>{item.identity.fullName}</strong><div className="small">{item.identity.employeeId || "Employee ID not verified"}</div></td><td>{item.identity.department || "Not verified"}</td><td className="mono">{item.device.deviceId}</td><td className="mono">{short(item.wallet.address)}</td><td>{formatDate(item.identity.createdAt)}</td><td><button className="action-link" onClick={() => { setSelected(item); setForm({ employeeId: item.identity.employeeId || "", department: item.identity.department || "" }); setRole(item.identity.role || "ENGINEER"); }}>Review →</button></td></tr>)}</tbody></table>{!pending.length && <Empty>No pending registrations.</Empty>}</div></Card>
    <Card><h2>Active employees and users <Badge tone="active">{active.length} active</Badge></h2><div className="table-wrap"><table><thead><tr><th>Name</th><th>Employee ID</th><th>Role</th><th>Department</th><th>Status</th><th /></tr></thead><tbody>{active.map((entry) => <tr key={entry.user.identityId}><td><strong>{entry.fullName}</strong></td><td>{entry.user.employeeId}</td><td>{entry.user.role}</td><td>{entry.user.department}</td><td><Badge tone="active">{entry.user.status}</Badge></td><td><button className="action-link" onClick={() => setViewed(entry)}>View →</button></td></tr>)}</tbody></table>{!active.length && <Empty>No active employees.</Empty>}</div></Card>
    {viewed && <div className="modal-backdrop"><Card className="modal"><div className="page-head"><div><div className="eyebrow">Employee details</div><h2>{viewed.fullName}</h2></div><button className="action-link" onClick={() => setViewed(null)}>Close</button></div><div className="kv"><div className="k">Employee ID</div><div className="v">{viewed.user.employeeId}</div><div className="k">Identity</div><div className="v mono">{viewed.user.identityId}</div><div className="k">Role</div><div className="v">{viewed.user.role}</div><div className="k">Department</div><div className="v">{viewed.user.department}</div><div className="k">Status</div><div className="v">{viewed.user.status}</div><div className="k">Wallet</div><div className="v mono">{viewed.user.walletAddress || "Not bound"}</div></div></Card></div>}
    {selected && <div className="modal-backdrop"><Card className="modal"><div className="page-head"><div><div className="eyebrow">Identity administration</div><h2>Review registration</h2></div><button className="action-link" onClick={() => setSelected(null)}>Close</button></div><div className="notice">Only public device and wallet information is shown. Private-key material is never submitted by onboarding.</div><div className="kv" style={{ marginTop: 20 }}><div className="k">Identity</div><div className="v">{selected.identity.identityId}</div><div className="k">Device</div><div className="v mono">{selected.device.deviceId} · {selected.device.status}</div><div className="k">Wallet</div><div className="v mono">{selected.wallet.address} · {selected.wallet.status}</div></div><div className="form-row" style={{ marginTop: 20 }}><div className="field"><label>Verified employee ID</label><input value={form.employeeId} onChange={(e) => setForm({ ...form, employeeId: e.target.value })} /></div><div className="field"><label>Verified department</label><input value={form.department} onChange={(e) => setForm({ ...form, department: e.target.value })} /></div></div><div className="field"><label>Authoritative role</label><select value={role} onChange={(e) => setRole(e.target.value as Role)}>{ROLES.map((r) => <option key={r}>{r}</option>)}</select></div><div className="actions"><Button onClick={verify} disabled={Boolean(busy) || verified}>{busy === "verify" ? "Verifying…" : verified ? "Identity verified" : "Verify information"}</Button><Button onClick={assign} disabled={Boolean(busy) || !verified || roleAssigned}>{busy === "role" ? "Assigning…" : roleAssigned ? "Role assigned" : "Assign role"}</Button><Button onClick={activate} disabled={Boolean(busy) || !verified || !roleAssigned}>{busy === "activate" ? "Activating…" : "Activate registration"}</Button><Button variant="secondary" onClick={() => setSelected(null)}>Close</Button></div></Card></div>}</>;
}
